

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      partner-1: "insa"
      partner-2: "idea"
      sponsor-1: "neosoft"
      sponsor-2: "bonitasoft"